# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-17 23:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Subjects')),
            ],
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='subject_id',
        ),
        migrations.AddField(
            model_name='tasks',
            name='variant_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tasks.Variant'),
            preserve_default=False,
        ),
    ]
